// <auto-generated />
namespace DotNet.MyProject.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SampleCodeFirst : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SampleCodeFirst));
        
        string IMigrationMetadata.Id
        {
            get { return "201808160853586_SampleCodeFirst"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
